<table cellpadding="5">
<tr>
<td>	
	<a href="http://www.cityofboston.gov/assessing/contactform.asp"><b>Contact</b></a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/default.asp"><b>Assessing Home</b></a>
	<br><br>
	<a href="https://www.cityofboston.gov/assessing/rent/">Apartment/Lodging Rent Information Requisition</a>
	<!--
	<a href="http://www.cityofboston.gov/assessing/search"><b><i>FY 2005 3rd Quarter<br>Certified Property Values</i></b></a>-->
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/mod_inc_sen.asp">State Income Tax Refund Credit</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/abatement.asp">Abatement Procedures</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/consildation.asp">Real Estate Parcel Consolidation</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/search/">Assessing On-line</a>	
	<br><br>
	<a href="http://www.cityofboston.gov/trac/faq03.asp">Frequently Asked Questions</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/facts.asp">Facts and Figures</a>
	<br><br>
	<a href="http://www.cityofboston.gov/trac/forms.asp">Forms</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/commissioner.asp">Letter from the Commissioner</a><br><br>
	<a href="http://www.cityofboston.gov/realestate">Make a Property Tax Payment</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/paysearch.asp">Payment Information</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/perproprty.asp">Personal Property</a>
	<br><br>
	<a href="http://www.cityofboston.gov/trac/clauses.asp">Personal Exemptions</a>
	<br><br>
	<a href="http://www.cityofboston.gov/trac/howto.asp">How to Apply for Personal Exemptions</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/resexempt.asp">Residential Exemptions</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/chariexemp.asp">Statutory Exemptions</a>
	<br><br>	
	<a href="http://www.cityofboston.gov/assessing/humanresources.asp">Human Resources</a>
	<br><br>
	<a href="http://www.cityofboston.gov/assessing/contacts.asp">Useful Contacts</a>
	
	<br><br>
	
</td>
</tr>
</table>	

