<!-- leftColBlue2Lines contains all leftColumn Navigation when the image is 2Lines -->
<td class="leftColBlue2Lines">
<div class="leftColHeader">
								<img src="/images/headWhiteLarge2LinesAssessingDepartment.gif" alt="Assessing Department"
									 align="left" />
							</div>
							<!-- leftColLinks is used for the upper left navigation rows -->
							<div class="leftColLinks" style="width: 235px;">
								<!-- Use leftColBulletOn and leftColLinkOn classes to denote the current page -->	
		<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
		<a class="leftColLinkOff" href="/assessing/contactform.asp"><b>Contact</b></a>
			</div>
	</div>

	
<div class="leftColBlueSpacer">
	<div class="leftColBullet">&nbsp;</div>
		<div class="leftColBlueLinkRow">
	<a class="leftColLinkOff" href="/assessing/default.asp">Assessing Home</b></a>
		</div>
</div>	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
		<a class="leftColLinkOff" href="/assessing/commissioner.asp">Letter from the Commissioner</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/assessing/search/">Assessing On-line</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/assessing/abatement.asp">Abatement Procedures</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/trac/faq/assessing_values.asp">Assessed Values</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/trac/faq03.asp?ID=16">Boat Excise</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
	<a class="leftColLinkOff" href="/trac/faq03.asp?ID=16">Boat Mooring/Docking Compliance Law/Permits</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/trac/forms.asp">Forms</a>
			</div>
	</div>
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/trac/faq/">Frequently Asked Questions</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/trac/faq/Motor_Vehicle_Excise.asp">Motor Excise</a>
			</div>
	</div>
	
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/trac/clauses.asp">Personal Exemptions</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/assessing/perproprty.asp">Personal Property</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
	<a class="leftColLinkOff" href="/assessing/consolidation.asp">Real Estate Parcel Consolidation</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/assessing/resexempt.asp">Residential Exemptions</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/assessing/chariexemp.asp">Statutory Exemptions</a>
			</div>
	</div>
	
	
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
			<a class="leftColLinkOff" href="/trac/faq03.asp?ID=6">Tax Rates</a>
			</div>
	</div>
		
	</div>
	
	<!-- leftColLinks02 is used for all lower left navigation -->
	    <div class="leftColLinks02">
	    <div class="leftColSubTitleBlue">Contact Us</div>
	    <div class="leftColSubLink">
		<a href="/contact/default.asp" class="leftColSubLink">Departments & Employees</a>
    </div>
	
	
	
</div>
<!-- leftColLinks02 is used for all lower left navigation -->
    <div class="leftColLinks02">
    <div class="leftColSubTitleBlue">Contact Us</div>
    <div class="leftColSubLink">
	<a href="/contact/default.asp" class="leftColSubLink">Departments & Employees</a>
    </div>