								
<div class="rightColModule2Lines">
<img src="/images/headBlue2LinesDepartmentAnnouncements.gif" 										 alt="Department Announcements" hspace="0" vspace="0" height="56" width="145" />

<div class="rightColModuleBlockBottom">
<a href="/assessing/pdfs/FY07_TaxCycle.pdf" class="rightColBoldLink">Fiscal Year 2007 Tax Bill Cycle Begins</a> 
<br />

<span class="rightColText">
The Fiscal Year 2007 tax billing cycle for real estate and personal property begins July 1st.
</span><br />

<a href="/assessing/pdfs/FY07_TaxCycle.pdf" class="rightColLink">Read details <b>&raquo;</b></a>
			</div>

<div class="rightColModuleBlockBottom">
<a href="/assessing/pdfs/FY07An_MainPro.pdf" class="rightColBoldLink">FY 2007 Annual Property Maintenance Project</a>
<br />

<span class="rightColText">
Assessors will be inspecting properties in certain neighborhoods...</span><br />
<a href="/assessing/pdfs/FY07An_MainPro.pdf" class="rightColLink">Read details <b>&raquo;</b></a>
						</div>
			</div>

			
			<!-- End rightCol Module -->
								
														
<!-- rightColModule is used when your right column contains a 2Line graphic header -->




<div class="rightColModule">
<img src="/images/headBlueRelatedLinks.gif"
	 alt="Related Links" hspace="0" vspace="0" height="36" width="119" />



		<div class="rightColModuleBlockBottom">
<a href="http://www.mass.gov/atb/" target="_blank" class="rightColLink">Appellate Tax Board (ATB)<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>

	</div>

<div class="rightColModuleBlockBottom">
<a href="http://www.dor.state.ma.us/" target="_blank" class="rightColLink">Massachusetts Department of Revenue (DOR)<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>

	</div>

<div class="rightColModuleBlockBottom">
<a href="http://www.dls.state.ma.us/" target="_blank" class="rightColLink">Massachusetts Department of Revenue Division of Local Services (DLS)<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>

	</div>


<div class="rightColModuleBlockBottom">
<a href="http://www.suffolkdeeds.com/" target="_blank" class="rightColLink">Suffolk County Registry of Deeds<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>			

	</div>


<div class="rightColModuleBlockBottom">
<a href="/archivesandrecords/sources.asp" target="_blank" class="rightColLink">City of Boston Archives<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>	
			</div>
	
<div class="rightColModuleBlockBottom">
<a href="http://www.adobe.com/products/acrobat/readstep2.html"
		  target="_blank" class="rightColLink">Get Adobe Reader</a><br />
		Many forms are available in PDF format.  To view and print in PDF format, you must download and install the reader.<br />

<a href="http://www.adobe.com/products/acrobat/readstep2.html" target="_blank">
		<br><img src="/images/iconGetAdobeReader.gif" alt="Get Adobe Reader" /></a>
	</div>
</div>		