<!-- leftColBluecontains all leftColumn Navigation when the image is 2Lines -->
<td class="leftColBlue">
	<div class="leftColHeader">
		<img src="/images/headWhiteLargeAssessing.gif" alt="Assessing Department" align="left" />
	</div>
	<!-- leftColLinks is used for the upper left navigation rows -->
	<div class="leftColLinks" style="width: 235px;">

	<!-- Use leftColBulletOn and leftColLinkOn classes to denote the current page -->	

	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/default.asp">Home</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/commissioner.asp">Letter from the Commissioner</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/search/">Assessing Online</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/abatement.asp">Abatement Procedures</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/assessedvalues.asp">Assessed Values</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/betterments_taxbill.asp">Betterments and Tax Bills</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/boatexcise.asp">Boat Excise</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/boats/mooring">Boat Mooring/ Docking Compliance Law/ Permits</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/mod_inc_sen.asp">Circuit Breaker Income Tax Credit</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/exemptions/">Exemptions</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/condoconversion.asp">Condo Conversion</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/assessing_data.asp">Data &amp; Mapping Resources</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/forms.asp">Forms</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/faq.asp">Frequently Asked Questions</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/Motor_Vehicle_Excise.asp">Motor Vehicle Excise</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/treasury/collecting/municipal_liens.asp">Municipal Liens</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/perproprty.asp">Personal Property</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/PILOT.asp">PILOT Task Force</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/propclass.asp">Property Classification</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/propid.asp">Property Identification</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/prop2half.asp">Proposition 2 1/2</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/consolidation.asp">Real Estate Parcel Consolidation</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/retaxes_bills_payments.asp">Real Estate Taxes Tax Bills and Payments</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/taxrates.asp">Tax Rates</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/taxdeferral.asp">Tax Deferral</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/trac.asp">Taxpayer Referral &amp; Assistance Center</a>
			</div>
	</div>
	<div class="leftColBlueSpacer">
		<div class="leftColBullet">&nbsp;</div>
			<div class="leftColBlueLinkRow">
				<a class="leftColLinkOff" href="/assessing/reval.asp">Triennial Revaluation</a>
			</div>
	</div>

</div>

<!-- leftColLinks02 is used for all lower left navigation -->
<div class="leftColLinks02" id="leftColLinks02">
	<div class="leftColSubTitleBlue">Contact Us</div>
	<div class="leftColSubLink">
		<a href="/assessing/contactform.asp" class="leftColSubLink">Assessing Department</a>
	</div>