<div class="rightColModule2Lines">
<img src="/images/headBlue2LinesDepartmentAnnouncements.gif" 										 alt="Department Announcements" hspace="0" vspace="0" height="56" width="145" />
	
	
<div class="rightColModuleBlockBottom">
<a href="/assessing/res_sales_prop.asp" class="rightColBoldLink">2013-2014 Residential Sales by Type</a>
<br />

<span class="rightColText">
View 2013-2014 sales of residential property
</span><br />

<a href="/assessing/res_sales_prop.asp" class="rightColLink"><b>&raquo;</b></a>
			</div>			


		</div>		
			<!-- End rightCol Module -->
								
														
														
<!-- rightColModule is used when your right column contains a 2Line graphic header -->




<div class="rightColModule">
<img src="/images/headBlueRelatedLinks.gif"
	 alt="Related Links" hspace="0" vspace="0" height="36" width="119" />



		<div class="rightColModuleBlock">
<a href="http://www.mass.gov/atb/" target="_blank" class="rightColLink">Appellate Tax Board (ATB)<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>

	</div>

<div class="rightColModuleBlock">
<a href="http://www.dor.state.ma.us/" target="_blank" class="rightColLink">Massachusetts Department of Revenue (DOR)<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>

	</div>

<div class="rightColModuleBlock">
<a href="http://www.dls.state.ma.us/" target="_blank" class="rightColLink">Massachusetts Department of Revenue Division of Local Services (DLS)<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>

	</div>


<div class="rightColModuleBlock">
<a href="http://www.suffolkdeeds.com/" target="_blank" class="rightColLink">Suffolk County Registry of Deeds<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>			

	</div>


<div class="rightColModuleBlock">
<a href="/archivesandrecords/sources.asp" target="_blank" class="rightColLink">City of Boston Archives<img src="/images/iconExternalLink.gif" vspace="0" alt="External Link" />												  
	</a>	
			</div>
	
</div>